### ISSUE TITLE
cannot package update due to autointf breakage

### ISSUE THREAD

**Issue by kubo39** [kubo39/deth#9]
```console
$ dub build
    Fetching vibe-core 2.9.5 (getting selected version)
    Fetching eventcore 0.9.34 (getting selected version)
    Fetching vibe-d 0.10.1 (getting selected version)
    Fetching vibe-stream 1.1.1 (getting selected version)
    Fetching vibe-serialization 1.0.5 (getting selected version)
    Fetching vibe-http 1.1.2 (getting selected version)
    Fetching diet-ng 1.8.2 (getting selected version)
    Fetching openssl 3.3.4 (getting selected version)
     Pre-gen Running commands for openssl
    Starting Performing "debug" build using /home/kubo39/dlang/ldc-1.39.0/bin/ldc2 for x86_64.
  Up-to-date keccak-tiny 1.2.1: target for configuration [library] is up to date.
  Up-to-date secp256k1 2.5.1: target for configuration [library] is up to date.
  Up-to-date structjson 2.100.1: target for configuration [library] is up to date.
  Up-to-date stdx-allocator 2.77.5: target for configuration [library] is up to date.
    Building vibe-container 1.3.1: building configuration [library]
    Building vibe-d:utils 0.10.1: building configuration [library]
    Building autointf 1.2.0: building configuration [library]
/home/kubo39/.dub/packages/autointf/1.2.0/autointf/source/autointf.d(10,8): Error: unable to read module `uda`
/home/kubo39/.dub/packages/autointf/1.2.0/autointf/source/autointf.d(10,8):        Expected 'vibe/internal/meta/uda.d' or 'vibe/internal/meta/uda/package.d' in one of the following import paths:
import path[0] = /home/kubo39/.dub/packages/autointf/1.2.0/autointf/source/
import path[1] = /home/kubo39/.dub/packages/vibe-d/0.10.1/vibe-d/utils
import path[2] = /home/kubo39/.dub/packages/vibe-container/1.3.1/vibe-container/source/
import path[3] = /home/kubo39/.dub/packages/stdx-allocator/2.77.5/stdx-allocator/source/
import path[4] = /home/kubo39/dlang/ldc-1.39.0/bin/../import
Error /home/kubo39/dlang/ldc-1.39.0/bin/ldc2 failed with exit code 1.
```
